---

- name: Create {{ smartpan_service_group }} group
  group:
    name: "{{ smartpan_service_group }}"
    state: present
    system: yes

- name: Create {{ smartpan_service_user }} user
  user:
    name: "{{ smartpan_service_user }}"
    shell: /bin/bash
    groups: "{{ smartpan_service_group }}"
    append: yes
    system: yes

- name: Set ownership and permissions for root directory of mounted filesystem
  file:
    path: "{{ smartpan_work_directory }}"
    owner: "{{ smartpan_service_user }}"
    group: "{{ smartpan_service_group }}"
    mode: '0755'
    state: directory

- name: Create temporary directory
  tempfile:
    state: directory
  register: temp_dir

- name: Download GoPAN tarball
  aws_s3:
    bucket: "{{ resource_bucket_name }}"
    object: "{{ resource_bucket_smartpan_prefix }}/gopan-{{ gopan_version }}-linux_amd64.tar.gz"
    dest: "{{ temp_dir.path }}/gopan-{{ gopan_version }}-linux_amd64.tar.gz"
    mode: get

- name: Extract GoPAN tarball
  unarchive:
    remote_src: yes
    src: "{{ temp_dir.path }}/gopan-{{ gopan_version }}-linux_amd64.tar.gz"
    dest: "{{ temp_dir.path }}"

- name: Install SmartPAN
  copy:
    src: "{{ temp_dir.path }}/smartpan"
    dest: "{{ smartpan_binary_directory }}/smartpan"
    owner: root
    group: root
    remote_src: yes
    mode: 0755

- name: Install dnf-plugins-core for access to config-manager
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Install cpanm
  command: curl -L https://cpanmin.us | perl - --sudo App::cpanminus
  args:
    warn: false 

- name: Install JSON-XS perl package
  community.general.cpanm:
    name: JSON::XS

- name: Install cpanm-managed SmartPAN dependencies
  cpanm:
    name: Parse::LocalDistribution

- name: Remove temporary directory
  file:
    path: temp_dir.path
    state: absent
